ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS anchor_tx_id TEXT,
  ADD COLUMN IF NOT EXISTS anchor_hash TEXT,
  ADD COLUMN IF NOT EXISTS anchor_simulated BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS anchor_explorer_url TEXT,
  ADD COLUMN IF NOT EXISTS anchored_at TIMESTAMPTZ;
