ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS anchor_tx_id TEXT,
  ADD COLUMN IF NOT EXISTS anchor_hash TEXT,
  ADD COLUMN IF NOT EXISTS anchor_simulated BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS anchor_explorer_url TEXT,
  ADD COLUMN IF NOT EXISTS anchored_at TIMESTAMPTZ;

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS company_name TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS zip TEXT;
